spring:
    application:
        name: backend
    datasource:
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
        username: ${POSTGRES_USER}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
